package com.crk.custom_report.modle;

public class DataSourceEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.data_source_id
     *
     * @mbggenerated
     */
    private String dataSourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.data_source_name
     *
     * @mbggenerated
     */
    private String dataSourceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.data_source_type
     *
     * @mbggenerated
     */
    private String dataSourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.sort
     *
     * @mbggenerated
     */
    private String sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.connect_url
     *
     * @mbggenerated
     */
    private String connectUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.connect_user
     *
     * @mbggenerated
     */
    private String connectUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.connect_password
     *
     * @mbggenerated
     */
    private String connectPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.connect_driver
     *
     * @mbggenerated
     */
    private String connectDriver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.ext1
     *
     * @mbggenerated
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.ext2
     *
     * @mbggenerated
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_source.ext3
     *
     * @mbggenerated
     */
    private String ext3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.data_source_id
     *
     * @return the value of data_source.data_source_id
     *
     * @mbggenerated
     */
    public String getDataSourceId() {
        return dataSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.data_source_id
     *
     * @param dataSourceId the value for data_source.data_source_id
     *
     * @mbggenerated
     */
    public void setDataSourceId(String dataSourceId) {
        this.dataSourceId = dataSourceId == null ? null : dataSourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.data_source_name
     *
     * @return the value of data_source.data_source_name
     *
     * @mbggenerated
     */
    public String getDataSourceName() {
        return dataSourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.data_source_name
     *
     * @param dataSourceName the value for data_source.data_source_name
     *
     * @mbggenerated
     */
    public void setDataSourceName(String dataSourceName) {
        this.dataSourceName = dataSourceName == null ? null : dataSourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.data_source_type
     *
     * @return the value of data_source.data_source_type
     *
     * @mbggenerated
     */
    public String getDataSourceType() {
        return dataSourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.data_source_type
     *
     * @param dataSourceType the value for data_source.data_source_type
     *
     * @mbggenerated
     */
    public void setDataSourceType(String dataSourceType) {
        this.dataSourceType = dataSourceType == null ? null : dataSourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.sort
     *
     * @return the value of data_source.sort
     *
     * @mbggenerated
     */
    public String getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.sort
     *
     * @param sort the value for data_source.sort
     *
     * @mbggenerated
     */
    public void setSort(String sort) {
        this.sort = sort == null ? null : sort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.connect_url
     *
     * @return the value of data_source.connect_url
     *
     * @mbggenerated
     */
    public String getConnectUrl() {
        return connectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.connect_url
     *
     * @param connectUrl the value for data_source.connect_url
     *
     * @mbggenerated
     */
    public void setConnectUrl(String connectUrl) {
        this.connectUrl = connectUrl == null ? null : connectUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.connect_user
     *
     * @return the value of data_source.connect_user
     *
     * @mbggenerated
     */
    public String getConnectUser() {
        return connectUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.connect_user
     *
     * @param connectUser the value for data_source.connect_user
     *
     * @mbggenerated
     */
    public void setConnectUser(String connectUser) {
        this.connectUser = connectUser == null ? null : connectUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.connect_password
     *
     * @return the value of data_source.connect_password
     *
     * @mbggenerated
     */
    public String getConnectPassword() {
        return connectPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.connect_password
     *
     * @param connectPassword the value for data_source.connect_password
     *
     * @mbggenerated
     */
    public void setConnectPassword(String connectPassword) {
        this.connectPassword = connectPassword == null ? null : connectPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.connect_driver
     *
     * @return the value of data_source.connect_driver
     *
     * @mbggenerated
     */
    public String getConnectDriver() {
        return connectDriver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.connect_driver
     *
     * @param connectDriver the value for data_source.connect_driver
     *
     * @mbggenerated
     */
    public void setConnectDriver(String connectDriver) {
        this.connectDriver = connectDriver == null ? null : connectDriver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.ext1
     *
     * @return the value of data_source.ext1
     *
     * @mbggenerated
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.ext1
     *
     * @param ext1 the value for data_source.ext1
     *
     * @mbggenerated
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.ext2
     *
     * @return the value of data_source.ext2
     *
     * @mbggenerated
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.ext2
     *
     * @param ext2 the value for data_source.ext2
     *
     * @mbggenerated
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column data_source.ext3
     *
     * @return the value of data_source.ext3
     *
     * @mbggenerated
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column data_source.ext3
     *
     * @param ext3 the value for data_source.ext3
     *
     * @mbggenerated
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }
}