spring:
  devtools:
    restart:
      enabled: false
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    name: default
    url: jdbc:mysql://localhost:3306/mydatabase?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 941021
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 192.168.5.188
    port: 6379
    password: tj720!@
server:
  port: 8181
  servlet:
    path: /customReport
  thymeleaf:
    cache: false
  tomcat:
    access_log_enabled: true
    basedir: target/tomcat
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.crk.custom_report.modle
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
