package com.crk.custom_report.dao;

import com.crk.custom_report.modle.DataSourceEntity;
import com.crk.custom_report.modle.DataSourceEntityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;
@Repository
public interface DataSourceEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbggenerated
     */
    int countByExample(DataSourceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbggenerated
     */
    int deleteByExample(DataSourceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbggenerated
     */
    int insert(DataSourceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbggenerated
     */
    int insertSelective(DataSourceEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbggenerated
     */
    List<DataSourceEntity> selectByExample(DataSourceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DataSourceEntity record, @Param("example") DataSourceEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_source
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DataSourceEntity record, @Param("example") DataSourceEntityExample example);
}